#!/usr/bin/env python

# Copyright 2016 DIANA-HEP
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse

class Formatter(argparse.HelpFormatter):
    def _fill_text(self, text, width, indent):
        return "\n".join(textwrap.fill(x, width) for x in text.splitlines())

if __name__ == "__main__":
    argumentParser = argparse.ArgumentParser(description="""The femtocode-populate tool fills a database or file with a properly-formatted Dataset (JSON) from a user-written Description (YAML).

The format of the YAML Description and JSON Dataset depends on the type of backend (e.g. numpyio or rootio). The destination file or database is also configurable.

The process of building a Dataset from a Description involves an examination of the data files to check for conformance with the stated schema and may be time-consuming. It is undertaken by the femtocode-server maintainer, not ordinary users.
""", formatter_class=Formatter)
